authorName: Unknown
experimentName: enas_macro
trialConcurrency: 2
maxExecDuration: 24h
maxTrialNum: 10
#choice: local, remote
trainingServicePlatform: local
#choice: true, false
useAnnotation: false
multiPhase: true
tuner:
  codeDir: ~/nni/examples/tuners/enas
  classFileName: nni_controller_ptb.py
  className: ENASTuner
  classArgs:
    say_hello: "hello"

trial:
  command: ./script/ptb_child.sh
  codeDir: ~/nni/examples/trials/enas
  gpuNum: 1
